wandb:
  project: vevo-series
  group:
  name: vevo-radflow
  tags:
    - vevo
    - radflow
    - time-series
  notes: Reproduced best experiment on VEVO dataset with Radflow.
datastore:
  type: vevo
  data_path: /localdata/u4921817/projects/phd/radflow/data/vevo/vevo_static.hdf5
  train_id_path: /localdata/u4921817/projects/phd/radflow/data/vevo/vevo_all_nodes.pkl
  test_id_path: /localdata/u4921817/projects/phd/radflow/data/vevo/vevo_static_connected_nodes.pkl
  batch_size: 64
  n_workers: 4
experiment:
  type: radflow
  rnn:
    type: radflow_lstm
    n_layers: 8
    hidden_size: 128
    input_size: 1
    dropout: 0.1
  forecast_length: 7
  backcast_length: 42
  copying_previous_day: true
trainer:
  gpus: 1
  precision: 32
  max_epochs: 20
