# Reproduce Table 1 in Norcliffe et al (2021)
comet:
  project_name: neural-ode
  experiment_name: baseline-sine-nodep
train_data_loader:
  dataset:
    type: sine
    amplitude_range: [-1.0, 1.0]
    freq_range: [1, 1]
    shift_range: [-0.5, 0.5]
    num_samples: 490
    seed: 41241
  batch_size: 5
  shuffle: true
  num_workers: 4
valid_data_loader:
  dataset:
    type: sine
    amplitude_range: [-1.0, 1.0]
    shift_range: [-0.5, 0.5]
    freq_range: [1, 1]
    num_samples: 10
    seed: 51343
  batch_size: 5
  shuffle: false
  num_workers: 4
system:
  type: time_series_ode
  num_context_range: [1, 10]
  extra_target_range: [0, 5]
  process:
    type: neural_ode_process
    x_dim: 1
    y_dim: 1
    r_dim: 50
    z_dim: 50
    h_dim: 50
    L_dim: 10
    initial_x: -3.2
    encoder:
      type: encoder
      x_dim: 1
      y_dim: 1
      h_dim: 50
      r_dim: 50
    decoder:
      type: mlp_ode_decoder
      x_dim: 1
      y_dim: 1
      z_dim: 50
      h_dim: 50
      L_dim: 10
      initial_x: -3.2
trainer:
  gpus: 1
  max_epochs: 40
  gradient_clip_val: 0.1
