name: rivernet
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - autopep8
  - cudatoolkit=11.0.221
  - cython
  - ipykernel
  - matplotlib
  - mypy
  - numpy=1.19.5
  - pandas
  - pip
  - pytorch=1.7.1
  - python=3.8 # pytorch_geometric doesn't yet support Python 3.9
  - pyyaml
  - torchvision
  - pip:
      - allennlp==1.3.0
      - docopt
      - einops
      - ipywidgets
      - jina
      - ogb
      - overrides
      - ptvsd
      - pudb
      - pymongo
      - schema
      - seaborn
      - tensorboard
      - tqdm
      - wget
