name: rivernet
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - autopep8
  - cython
  - ipykernel
  - matplotlib
  - mypy
  - numpy
  - pandas
  - pip
  - pytorch=1.8
  - python=3.8 # pytorch_geometric doesn't yet support Python 3.9
  - pyyaml
  - torchvision
  - pip:
      - allennlp==1.5.0
      - comet_ml
      - docopt
      - einops
      - hickle
      - ipywidgets
      - jina
      - netron # visualizes neural networks
      - ogb
      - overrides
      - plotly
      - ptvsd
      - pudb
      - pymongo
      - pytorch-lightning==1.2.2
      - ray # for hyperparameter tuning
      - schema
      - seaborn
      - tensorboard
      - torchdiffeq==0.2.1
      - torchdyn==0.2.2.1
      - git+https://github.com/patrick-kidger/torchcde.git
      - git+https://github.com/google-research/torchsde.git
      - tqdm
      - typer
      - wandb
      - wget
