[tool.poetry]
name = "fourierflow"
version = "0.3.0"
description = "Experiments with Fourier layers on simulation data."
authors = ["Alasdair Tran <alasdair.tran@anu.edu.au>"]
repository = "https://github.com/alasdairtran/fourierflow"

[tool.poetry.dependencies]
python = "~3.9.9"
# poetry add dask einops entmax gdown hyperopt ipykernel jupyterlab \
#   git+https://github.com/google/jax-cfd.git@f2446fe966386836680013d80f38eda4e0b48b5 \
#   matplotlib moviepy pandas plotly poethepoet ptvsd pydocstyle \
#   python-dotenv pytorch-lightning requests rich seaborn termcolor \
#   tensorflow-gpu tfrecord torchdiffeq torchtyping typer wandb xarray
dask = "^2021.12.0"
einops = "^0.3.2"
entmax = "^1.0"
gdown = "^4.2.0"
hydra-core = "^1.1.1"
hyperopt = "^0.2.7"
ipykernel = "^6.5.1"
jax-cfd = {git = "https://github.com/google/jax-cfd.git", rev = "f2446fe966386836680013d80f38eda4e0b48b53"}
jupyterlab = "^3.2.4"
matplotlib = "^3.5.0"
moviepy = "^1.0.3"
pandas = "^1.3.4"
plotly = "^5.4.0"
poethepoet = "^0.11.0"
ptvsd = "^4.3.2"
pydocstyle = "^6.1.1"
python-dotenv = "^0.19.2"
pytorch-lightning = "^1.5.3"
requests = "^2.26.0"
rich = "^10.15.0"
seaborn = "^0.11.2"
termcolor = "^1.1.0"
tensorflow-gpu = "^2.7.0"
tfrecord = "^1.14.1"
torchdiffeq = "^0.2.2"
torchtyping = "^0.1.4"
typer = "^0.4.0"
wandb = "^0.12.7"
xarray = "^0.20.1"

[tool.poetry.dev-dependencies]
# poetry add --dev autopep8 ipympl isort mypy pylint types-requests
autopep8 = "^1.6.0"
ipympl = "^0.8.2"
isort = "^5.10.1"
mypy = "^0.910"
pylint = "^2.12.1"
types-requests = "^2.26.1"

[tool.poetry.scripts]
fourierflow = 'fourierflow.commands.__main__:app'

[tool.poe.tasks]
# Remove when this is fixed: https://github.com/python-poetry/poetry/issues/2613
install-torch-cuda11 = "python -m pip install --no-cache-dir -U torch==1.10.0+cu113 torchvision==0.11.1+cu113 torchaudio==0.10.0+cu113 -f https://download.pytorch.org/whl/torch_stable.html"
install-jax-cuda11 = "python -m pip install -U \"jax[cuda]\" -f https://storage.googleapis.com/jax-releases/jax_releases.html"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.pylint.messages_control]
disable = [
    "cyclic-import", # disabled until https://github.com/PyCQA/pylint/issues/3525 is fixed
    "invalid-name",
    "logging-fstring-interpolation", # f-strings are faster
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring",
    "no-else-return",
    "no-member",
    "no-self-argument",
    "no-self-use",
    "redefined-builtin",
    "too-few-public-methods",
    "unused-argument",
]

[tool.pylint.similarities]
# Minimum lines number of a similarity.
min-similarity-lines = 5
# Ignore imports when computing similarities.
ignore-imports = "yes"

[tool.isort]
src_paths = ["fourierflow"]
