[tool.poetry]
name = "fourierflow"
version = "0.1.0"
description = "Exploration of neural ODE processes and Fourier layers."
authors = ["Alasdair Tran <alasdair.tran@anu.edu.au>"]
repository = "https://github.com/alasdairtran/fourierflow"

[tool.poetry.dependencies]
python = "^3.8.9"
# poetry add allennlp einops entmax gdown hyperopt ipykernel jupyterlab jupyterlab \
#   matplotlib numpy pandas ptvsd pydocstyle pylint pytorch-lightning \
#   pytorch-lightning-bolts seaborn typer torch torchaudio \
#   git+https://github.com/patrick-kidger/torchcde.git \
#   wandb
allennlp = "^2.4.0"
einops = "^0.3.0"
entmax = "^1.0"
gdown = "^3.13.0"
hyperopt = "^0.2.5"
ipykernel = "^5.5.5"
jupyterlab = "^3.0.15"
matplotlib = "^3.4.2"
numpy = "^1.20.3"
pandas = "^1.2.4"
ptvsd = "^4.3.2"
pydocstyle = "^6.0.0"
pylint = "^2.8.2"
pytorch-lightning = "^1.3.1"
pytorch-lightning-bolts = "^0.3.2"
seaborn = "^0.11.1"
typer = "^0.3.2"
torch = "^1.8.1"
torchaudio = "^0.8.1"
torchcde = {git = "https://github.com/patrick-kidger/torchcde.git"}
wandb = "^0.10.30"

[tool.poetry.dev-dependencies]
# poetry add --dev mypy isort autopep8
mypy = "^0.812"
isort = "^5.8.0"
autopep8 = "^1.5.7"

[tool.poetry.scripts]
fourierflow = 'fourierflow.commands.__main__:app'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.pylint.messages_control]
disable = [
    "cyclic-import", # disabled until https://github.com/PyCQA/pylint/issues/3525 is fixed
    "invalid-name",
    "logging-fstring-interpolation", # f-strings are faster
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring",
    "no-else-return",
    "no-member",
    "no-self-argument",
    "no-self-use",
    "redefined-builtin",
    "too-few-public-methods",
    "unused-argument",
]

[tool.pylint.similarities]
# Minimum lines number of a similarity.
min-similarity-lines = 5
# Ignore imports when computing similarities.
ignore-imports = "yes"

[tool.isort]
src_paths = ["fourierflow"]
