wandb:
  project: vevo-series
  group:
  name: vevo-perceiver
  tags:
    - vevo
    - perceiver
    - time-series
  notes: Vevo with perceiver.
datastore:
  type: vevo
  data_path: /localdata/u4921817/projects/phd/radflow/data/vevo/vevo_static.hdf5
  train_id_path: /localdata/u4921817/projects/phd/radflow/data/vevo/vevo_all_nodes.pkl
  test_id_path: /localdata/u4921817/projects/phd/radflow/data/vevo/vevo_static_connected_nodes.pkl
  batch_size: 64
  n_workers: 4
experiment:
  type: nbeats
  model:
    type: time_series_perceiver
    num_freq_bands: 8
    depth: 8
    max_freq: 21
    input_channels: 1
    input_axis: 1
    num_latents: 64
    latent_dim: 80
    cross_heads: 1
    latent_heads: 8
    cross_dim_head: 10
    latent_dim_head: 10
    attn_dropout: 0
    ff_dropout: 0
    weight_tie_layers: false
    fourier_encode_data: true
    self_per_cross_attn: 1
    self_attn_rel_pos: true
  forecast_length: 7
  backcast_length: 42
trainer:
  gpus: 1
  precision: 32
  max_epochs: 20
