wandb:
  project: navier-stokes-4
  group:
  name: 08_perceiver
  tags:
    - pde
    - navier-stokes
    - fourier
  notes: Reproduced experiment of Li et al (2020)
datastore:
  type: navier_stokes
  data_path: ${FNO_DATA_ROOT}/NavierStokes_V1e-5_N1200_T20.mat
  train_size: 1000
  test_size: 200
  ssr: 1 # sub-sampling rate
  n_steps: 10
  batch_size: 20
  n_workers: 4
  append_pos: false
experiment:
  type: fourier_2d
  conv:
    type: perceiver
    num_freq_bands: 8
    depth: 4
    max_freq: 32
    freq_base: 2
    input_channels: 10
    input_axis: 2
    num_latents: 64
    latent_dim: 128
    cross_heads: 4
    cross_dim_head: 16
    num_classes: 1
    self_per_cross_attn: 0
  append_pos: false
  n_steps: 10
  optimizer:
    type: adamw
    lr: 0.0025
    weight_decay: 0.0001
  scheduler:
    type: step_lr
    step_size: 100
    gamma: 0.5
  scheduler_config:
    name: learning_rate
    interval: epoch
    frequency: 1
    monitor: None
trainer:
  gpus: 1
  precision: 32
  max_epochs: 500
checkpointer:
  validation_metric: valid_loss
