wandb:
  project: vevo-series
  group: copying-previous-day
  name: vevo-copy
  tags:
    - vevo
    - time-series
  notes: Reproduced baseline experiment on VEVO dataset by copying previous day.
datastore:
  type: vevo
  data_path: /localdata/u4921817/projects/phd/radflow/data/vevo/vevo_static.hdf5
  train_id_path: /localdata/u4921817/projects/phd/radflow/data/vevo/vevo_all_nodes.pkl
  test_id_path: /localdata/u4921817/projects/phd/radflow/data/vevo/vevo_static_connected_nodes.pkl
  batch_size: 64
  n_workers: 4
experiment:
  type: nbeats
  copying_previous_day: true
  forecast_length: 7
  backcast_length: 42
trainer:
  gpus: 1
  precision: 16
  max_epochs: 5
