wandb:
  project: vevo-series
  group:
  name: 07_perceiver_shared
  tags:
    - vevo
    - perceiver
    - time-series
  notes: Vevo with perceiver.
datastore:
  type: vevo
  data_path: /localdata/u4921817/projects/phd/radflow/data/vevo/vevo_static.hdf5
  train_id_path: /localdata/u4921817/projects/phd/radflow/data/vevo/vevo_all_nodes.pkl
  test_id_path: /localdata/u4921817/projects/phd/radflow/data/vevo/vevo_static_connected_nodes.pkl
  batch_size: 64
  n_workers: 4
experiment:
  type: nbeats
  model:
    type: time_series_perceiver
    num_freq_bands: 8
    depth: 8
    max_freq: 21
    input_channels: 1
    input_axis: 1
    input_dim: 64
    num_latents: 64
    latent_dim: 224
    cross_heads: 8
    latent_heads: 8
    cross_dim_head: 32
    latent_dim_head: 32
    attn_dropout: 0
    ff_dropout: 0
    weight_tie_layers: true
    fourier_encode_data: true
  forecast_length: 7
  backcast_length: 42
  optimizer:
    type: adamw
    lr: 0.0001
    weight_decay: 0.0001
  scheduler:
    type: linear_with_warmup
    num_warmup_steps: 5000
    num_training_steps: 95000
  scheduler_config:
    name: learning_rate
    interval: step
    frequency: 1
    monitor: None
trainer:
  gpus: 1
  precision: 16
  max_epochs: 100
  check_val_every_n_epoch: 10
  gradient_clip_val: 0.1
checkpointer:
  validation_metric: valid_smape
