wandb:
  project: navier-stokes-4
  group:
  name: 114_single_4_fourier
  tags:
    - pde
    - navier-stokes
    - fourier
  notes: Reproduced experiment of Li et al (2020)
datastore:
  type: navier_stokes_2
  data_path: ${FNO_DATA_ROOT}/NavierStokes_V1e-5_N1200_T20.mat
  train_size: 1000
  test_size: 200
  ssr: 1 # sub-sampling rate
  batch_size: 4
  n_workers: 4
experiment:
  type: fourier_2d_single
  conv:
    type: fourier_net_2d_split
    modes1: 16
    modes2: 16
    width: 32
    residual: true
    linear_out: true
    n_layers: 4
    input_dim: 35 # n_dims * ((n_freq_bands * 2) + 1)
  use_fourier_position: true
  max_freq: 32
  num_freq_bands: 8
  n_steps: 10
  optimizer:
    type: adamw
    lr: 0.0025
    weight_decay: 0.0001
  scheduler:
    type: cosine_with_warmup
    num_warmup_steps: 500
    num_training_steps: 12500
    num_cycles: 0.5
  scheduler_config:
    name: learning_rate
    interval: step
    frequency: 1
    monitor: None
trainer:
  gpus: 1
  precision: 32
  max_epochs: 50
checkpointer:
  validation_metric: valid_loss
