# Reproduce Table 1 in Norcliffe et al (2021)
comet:
  project_name: neural-ode
  experiment_name: complex-sine
train_data_loader:
  dataset:
    type: sine
    amplitude_range: [-1.0, 1.0]
    freq_range: [5, 5]
    shift_range: [-0.5, 0.5]
    num_samples: 490
    seed: 41241
  batch_size: 5
  shuffle: true
  num_workers: 4
valid_data_loader:
  dataset:
    type: sine
    amplitude_range: [-1.0, 1.0]
    shift_range: [-0.5, 0.5]
    freq_range: [5, 5]
    num_samples: 10
    seed: 51343
  batch_size: 5
  shuffle: false
  num_workers: 4
system:
  type: time_series_ode
  num_context_range: [20, 30]
  extra_target_range: [10, 20]
  process:
    type: neural_ode_process
    x_dim: 1
    y_dim: 1
    r_dim: 128
    z_dim: 128
    h_dim: 128
    L_dim: 32
    initial_x: -3.2
    agg: lstm
    xy_encoder:
      type: encoder
      x_dim: 1
      y_dim: 1
      h_dim: 128
      r_dim: 128
    r_encoder:
      type: mu_sigma_encoder
      r_dim: 128
      z_dim: 128
    decoder:
      type: mlp_ode_decoder
      x_dim: 1
      y_dim: 1
      z_dim: 128
      h_dim: 128
      L_dim: 32
      initial_x: -3.2
trainer:
  gpus: 1
  max_epochs: 40
  gradient_clip_val: 0.1
